### PR TITLE
nan: fix implementation for nan2 on linux

### PR DESCRIPTION
**Pull request by TomFreudenberg**
Hey after my last PR I run tests on linux and got those errors.

This will fix that and works fine.

I tested at:

MAC OSX
Ubuntu 14.0.4 x86_64
Ubuntu 14.04 armv7l
FreeBSD 10.2 amd64

all are fine by now

Sorry for sending faulty patch

### CODE REVIEW

**Comment by TomFreudenberg** [comment]
Hi @indutny , @santigimeno you should update quickly because current 1.0.0 npm on npmjs will break on linux platform.

Sorry for headache

**Comment by TomFreudenberg** [comment]
fixes #9

**Comment by indutny** [comment]
Landed, thank you! May I ask you to refrain from changing the npm version in Pull Requests? ;)

**Comment by TomFreudenberg** [comment]
Yes, sure sorry - won't do that anymore :-)

**Pull request closed without merging**
