### PR TITLE
Fix for newer node-nan release >1.5.1 - necessary e.g. for FreeBSD

### PR DESCRIPTION
**Pull request by TomFreudenberg**
Hi Fedor ( @indutny )

here you are ;-) 

I run the mocha tests with any issues, compiling test at MacOsx, Armv7l, FreeBSD where sucessfull.

Cheers
Tom

### CODE REVIEW

**Comment by TomFreudenberg** [comment]
This is a fix for issue #9

**Comment by indutny** [comment]
@TomFreudenberg I'm generally fine with the changes, however it does not seem to be working either ;) (perhaps only on some node.js versions). What do you think about updating nan to 2.1.0 instead?

**Comment by TomFreudenberg** [comment]
@indutny I will check for nan 2.1.0 - currently building

**Comment by TomFreudenberg** [comment]
See issue #9 - using 2.1.0 I get the documented errors

**Comment by TomFreudenberg** [comment]
I send in a new one and drop that here

**Pull request closed without merging**
